### ISSUE TITLE
Document output-spaces differences

### ISSUE THREAD

**Issue by dmd** [nipreps/fmriprep#2006]
Unless I've missed it somewhere, I don't see any one place that documents how `output-spaces` has changed; information seems to be distributed across several different issues.

In my particular case, I and @bbfrederick are interested to know whether our current site standard of `--output-spaces MNI152NLin2009cAsym:res-2 anat func fsaverage` will need to change under the new syntax.

**Comment by mgxd** [comment]
The bulk of the `--output-spaces` changes are for internal handling of normalizations, in an effort to reduce missing transforms within the workflow.  There is now a clear distinction between these internal spaces and user requested outputs, which should help reduce the amount of unwanted outputs generated by previous versions. 

Additionally, the refactoring of `--output-spaces` allows for multiple resolutions of the same template. For example, specifying
```
--output-spaces MNI152NLin2009cAsym:res-native:res-2
```
will produce BOLD outputs in MNI152 space with 2 difference resolutions: the native BOLD resolution and `res-2` resolution, which lines up with 2mm isotropic

The change should not require any changes to your current `--output-spaces`. The only difference to your outputs will be that the `MNI152NLin2009cAsym` BOLD outputs will have the resolution identifier in the filename.

**Comment by oesteban** [comment]
In addition to Mathias' comment, please let us know what you guys missed out on https://fmriprep.readthedocs.io/en/latest/spaces.html

**Comment by bbfrederick** [comment]
That’s an excellent and very clear write up - I hadn’t stumbled on that before!

I had two questions/suggestions. 
1) in our previous discussions, I learned that res-1 meant “at the resolution of template 1”, not “at a resolution of 1mm isotropic”. Now, coincidentally for res-1 and res-2, for the standard human templates, that’s the same thing. But unless something is changed in TemplateFlow it’s probably worth pointing that out, since the examples given imply otherwise. I’ve seen some discussion in the threads of an “iso-xx” modifier which is unambiguous, but my impression was that that was still in the discussion phase rather than in the released version, since that required implementation of arbitrary resolution resampling, which is nontrivial to do consistently and correctly. 
2) there is a special call out pointing out that data in spaces needed for intermediate calculations (like MNI152NLin6 for aroma) which are not specified in the output-spaces list are deleted after the results are resampled. That should be repeated in the last line of “Preprocessing blocks depending on standard templates”.

**Comment by oesteban** [comment]
> 1) in our previous discussions, I learned that res-1 meant “at the resolution of template 1”, not “at a resolution of 1mm isotropic”. Now, coincidentally for res-1 and res-2, for the standard human templates, that’s the same thing. But unless something is changed in TemplateFlow it’s probably worth pointing that out, since the examples given imply otherwise. I’ve seen some discussion in the threads of an “iso-xx” modifier which is unambiguous, but my impression was that that was still in the discussion phase rather than in the released version, since that required implementation of arbitrary resolution resampling, which is nontrivial to do consistently and correctly.

Yes, I've opened #2291. Yes, the ``res-iso2mm`` notation is not accepted. Because there's been little activity on this front, the issue is up for grabs. This could become a particularly low hanging fruit if templateflow/python-client#43 finally materializes.



> 2) there is a special call out pointing out that data in spaces needed for intermediate calculations (like MNI152NLin6 for aroma) which are not specified in the output-spaces list are deleted after the results are resampled. That should be repeated in the last line of “Preprocessing blocks depending on standard templates”.

#2292
