### ISSUE TITLE
Alignment problem

### ISSUE THREAD

**Issue by manzouri** [nipreps/fmriprep#2362]
![Screenshot 2021-02-01 at 12 02 22](https://user-images.githubusercontent.com/36534896/106588019-98c58980-654a-11eb-802a-85dc5cd046aa.png)
![Screenshot 2021-02-01 at 12 02 01](https://user-images.githubusercontent.com/36534896/106588036-9d8a3d80-654a-11eb-8b88-16faa78d8d75.png)

Hi, I am running fmriprep on my data acquired with Philips scanner. There is no PE direction and slice timing info in the json file but I can see from header that (0018,1312  Phase Encoding Direction: COL ) .Here is the settings :
Functional
Reports for: session 01, task faceloc, run 1.
Summary

    Repetition time (TR): 0.57s
    Phase-encoding (PE) direction: MISSING - Assuming Anterior-Posterior
    Single-echo EPI sequence.
    Slice timing correction: Not applied
    Susceptibility distortion correction: FLB ("fieldmap-less", SyN-based)
    Registration: FSL flirt with boundary-based registration (BBR) metric - 12 dof
    Non-steady-state volumes: 0

And I see that after alignment my functional data is stretched in occipital and frontal parts. I wonder if there is anything that I miss or can do to improve it?

**Comment by oesteban** [comment]
Just con confirm we are looking at the same area, it'd be nice that you added little arrows where you think the misalignment is worse.

That said, it seems that your susceptibility distortions (https://doi.org/10.31219/osf.io/gy8nt) are strong enough so our "fieldmap-less" estimation of the fieldmap does not fully account for distortions.

Unless you do have fieldmaps acquired and can feed them into fMRIPrep, there's honestly very little you can do otherwise. Except, perhaps, you can wait for improvements on SDCFlows, the component of fMRIPrep that tackles this problem. That said, the resources are very limited at this point so it is doubtful we'll have a breakthrough anytime soon.

**Comment by manzouri** [comment]
Hi and thanks for the reply. Now I added arrows to the regions. Unfortunately we didn't acquire fieldmaps and just to make sure that slice timing correction (which we don't have it from dicoms) won't help? It also a bit worse without SDC and with 6 dof registration.
![Screenshot 2021-02-01 at 12 02 01](https://user-images.githubusercontent.com/36534896/107497640-1dd82080-6b93-11eb-9a08-07280b02de8d.png)

**Comment by oesteban** [comment]
Yes, those are susceptibility distortions. I've seen much worse, but nonetheless, you will need to interpret the results of your analysis with care.

**Comment by manzouri** [comment]
Thanks a lot and looking forward to the improvements to SDCFlow.
