### ISSUE TITLE
fsaverage output not generated

### ISSUE THREAD

**Issue by satra** [nipreps/fmriprep#2388]
With the settings below, fMRIPrep is only generating fsLR output but not the fsaverage:den-40k output. any ideas how to enable both? The process finishes without any error.

### What version of fMRIPrep are you using?
20.2.1

### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
singularity

### What is the exact command-line you used?
```
/DATA/Caltech /BASE/Caltech_derivatives     participant --participant_label sub-0051456 
--output-layout bids     
--output-spaces MNI152NLin6Asym:res-2 fsaverage:den-40k T1w:res-2
--use-aroma     
--skip-bids-validation 
--fs-license-file /DATA/freesurfer_license.txt     
--fs-subjects-dir /BASE/Caltech_derivatives/freesurfer     
--cifti-output 
-w /BASE/fmriprep-workdir-abide/Caltech/sub-0051456
```

cc: @djarecka

**Comment by mgxd** [comment]
this looks like a bug - i think replacing `fsaverage:den-40k` with `fsaverage6` should do the trick for now

**Comment by effigies** [comment]
@mgxd has this been fixed?

**Comment by mgxd** [comment]
nope, though I would imagine the bug is somewhere here

https://github.com/nipreps/fmriprep/blob/369c941152b4a86ac4d7c6acfe318f509236b111/fmriprep/workflows/bold/outputs.py#L344-L352

**Comment by oesteban** [comment]
Sorry for joining late to the party.

I think the problem is that `den-40k` is not equivalent of any "legacy" fsaverages. `den-41k` would be (at least to the eyes of fMRIPrep).

So `--output-spaces fsaverage:den-41k` should do.

Mapping here: https://github.com/nipreps/niworkflows/blob/962c2344571ab080a415504daec0821a4877c6f4/niworkflows/utils/spaces.py#L49

cc/ @djarecka.

Please reopen if you think the mapping should be 40k and/instead of 41k.
