### ISSUE TITLE
Memory Configuration

### ISSUE THREAD

**Issue by cdlyr** [nipreps/fmriprep#2524]
Hi there,

It's a really nice toolbox. I am running fmriprep on HPC for a large dataset. However, even I've successfully processed hundreds of subjects, I am still confused about the memory configuration after reading the related posts from https://fmriprep.org/en/stable/faq.html#my-fmriprep-run-is-hanging. 

Currently for each job I gave 32GB memory via a `plugin.yml` file. But the log file still said "Some nodes exceed the total amount of memory available (32.00GB).". Actually, most jobs only used 10-15GB maximally for the entire time (the server can monitor the peak of memory usage). Rest of them came up with the memory allocation error, which may exceed the 32GB hard limit for each job. My temporary solution is to run a batch, i.e. 500 subjects, and then rerun the error subjects after the batch completes (roughly 20-50 error subjects per 500 attempts).

My question is whether there is a `memory_gb` value that can completely prevent the memory allocation error happen. Or, is it appropriate to lower the `memory_gb` to 15GB or 20GB to allow more jobs running simultaneously? Then I can rerun the error subjects more efficiently. Any advice and suggestions will be greatly appreciated.

I notice you've created a post named 'How to decide on nthreads/omp-nthreads/mem-gb'. It would be very nice if you can finish it sometime.

Thank you!

**Comment by oesteban** [comment]
> "Some nodes exceed the total amount of memory available (32.00GB).". Actually, most jobs only used 10-15GB maximally for the entire time (the server can monitor the peak of memory usage).

This is unsurprising as the workflows uses rough estimations of memory utilization baked in the code. Your estimation of 10-15GB is way more reliable than ours. You can safely dismiss this warning.

> Rest of them came up with the memory allocation error, which may exceed the 32GB hard limit for each job.

The problem here is how Python on Linux works. As Python never clears up memory pages (just writes them into virtual memory), plus how the subprocess module uses fork (instead of spawn) to create new processes, this becomes a problem on applications running thousands of processes (such as fMRIPrep). In this case, the best strategy is to limit parallelization by not running many subjects at once, and by reducing the number of parallel processes with `--nthreads` (e.g., `--nthreads 8` despite having 20 cpus). Some info can be found here - https://neurostars.org/t/how-much-ram-cpus-is-reasonable-to-run-pipelines-like-fmriprep/1086/5?u=oesteban

> My question is whether there is a `memory_gb` value that can completely prevent the memory allocation error happen. Or, is it appropriate to lower the `memory_gb` to 15GB or 20GB to allow more jobs running simultaneously? Then I can rerun the error subjects more efficiently. Any advice and suggestions will be greatly appreciated.

As I was mentioning above, you want fewer processes to be running in parallel at a given time. Especially, you don't want that a new process is launched while a currently running memory hog is taking up all memory. Because of the problem I mentioned before of Python and Linux, at the fork moment memory allocation will be doubled and your HPC will probably not allow overcommitting, which ends up with the OMM killer kicking in.

**Comment by cdlyr** [comment]
Thanks very much for your explanation. I never set the value of `--nthreads` before. The parameters I used to control the processes is all from `plugin.yml` that only includes `memory_gb` and `n_procs`. Maybe it's the reason for the Linux system to allow too many processes to run simultaneously. Nevertheless, running fmriprep on HPC saved a lot of time anyway.
