### ISSUE TITLE
What does the 'sloppy' flag do?

### ISSUE THREAD

**Issue by NickESouter** [nipreps/fmriprep#2960]
Hello!

I was just wondering if there's any documentation on what exactly the --sloppy flag does to an fMRIPrep pipeline? What is it actually doing to get everything running faster? It would be great to see a brief list of the specific steps involved.

Many thanks,

Nick

**Comment by effigies** [comment]
It uses more relaxed registration parameters so that the processes terminate more quickly at the cost of worse registrations. It is a development tool only intended to speed up workflow testing.

**Comment by NickESouter** [comment]
Thanks for the quick reply @effigies :) Just to clarify, for the relaxed parameters you mention here, presumably these changes are separate from any other changes you could make to the registration process in the command line? For example, does it involve limiting the ANTs registration process in some way, rather than something like just switching off BBR?

**Comment by effigies** [comment]
It does not turn of BBR since that's part of the workflow, but it provides alternative registration parameters. Mostly to ANTs, but also TOPUP. The different configurations will live alongside the interfaces that use them. For example, see the `_precise.json` and `_testing.json` parameter files in https://github.com/nipreps/niworkflows/tree/master/niworkflows/data or different FLIRT schedules for TOPUP in https://github.com/nipreps/sdcflows/tree/master/sdcflows/data/flirtsch.

**Comment by NickESouter** [comment]
This is a huge help, thank you :)
