### ISSUE TITLE
Flag for changing high pass filter for compcor

### ISSUE THREAD

**Issue by BAshinoff** [nipreps/fmriprep#2963]
### What would you like to see added in fMRIPrep?

Hi,

Thank you for all the work you've done on fMRIprep so far!

I was wondering if you could add a flag to set a custom high pass filter prior to the compcor calculations.
I have a task where I would like to use the compcor regressors, but I need a longer high pass filter than the default of 128 sec.

Thank you.

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance

**Comment by effigies** [comment]
You want to preserve signals <.0078Hz? Could you explain your use case a bit more?

**Comment by BAshinoff** [comment]
Hi,

I have a nested design, where I am modelling individual decisions that are part of a set of related decisions. I have included an example of a design matrix for one run (participants do 4 runs overall).

Within each trial (6 trials per run), participants make 9 decisions which I expect to influence each other over time. Based on this I think I need to use a high pass filter that won't filter out the increase in the effect of interest over the course of the trial. My understanding is that I need something at least 2x or 3x the longest trial for the high pass filter. So in this case, the longest trial is ~152sec, which is longer than the 128 sec default, so I need a high pass filter that is ~304sec (0.0032 Hz) or ~456sec (0.0022Hz). However, I am open to other suggestions. Thanks!

Brandon



![image](https://user-images.githubusercontent.com/58481618/224799565-b36f27d0-7b14-4409-9701-3383e4f47dff.png)

**Comment by effigies** [comment]
Okay. So I *think* that you can probably get away with using CompCor components that were constructed with a 128s high-pass cutoff.

The effect of high-pass filtering BOLD series before calculating confounds is so that the confounds will not have low-frequency components in them. Therefore, low-frequency components in your data should not be removed by the confounds we generate. You can now choose to create a different cosine basis with a higher high-pass cutoff, which will simply remove the higher-frequency cosines from your design matrix. All that will happen is that the CompCor components will not contain signals in the 304s-128s band, so you won't be *removing* that.

I would give it a shot this way. You can also try running a modified version of fMRIPrep where you add a `high_pass_cutoff` argument to these three nodes:

https://github.com/nipreps/fmriprep/blob/d14b81141303114a465d4364ec3962d88cedd4be/fmriprep/workflows/bold/confounds.py#L285-L328

If you see a significant difference, we can think about adding a flag to tweak this parameter.

**Comment by BAshinoff** [comment]
OK. I will give that a shot. 

Do I still have to also use the cosine functions generated by fmriprep as a regressor in addition to the new high-pass filter?

My understanding is that the cosine functions just apply the high-pass filter to the data, which is why the fmriprep documentation says you should include them if you use compcor. But if I am using a different high-pass filter, via SPM, then theoretically I don't need the cosine functions from fmriprep anymore. Is that accurate? Or is there some other reason to continue to include the cosine functions, even with the SPM high pass filter?

**Comment by jmumford** [comment]
Just a quick secondary note, your regressor actually looks like the signal of interest is high frequency.  The rule of thumb assumes your convolved regressors look like long blocks and yours do not since the different decisions (components of the trial) appear to have some fixation between them.  The concern is whether there's a collinearity between your model (more specifically the contrasts you're interested in) driven by the cosine basis set that is used.  If I'm designing a study or if I've just set up some design matrices for new data, I check the VIF of the contrasts to be sure we are okay, since it is far more complete than looking at pairwise regressor correlations to check for collinearity.  I wrote some code for this here https://github.com/jmumford/vif_contrasts

**Comment by effigies** [comment]
I don't have a strong argument for not using a different high-pass filter, but instinctively I would stick to a cosine basis (which should be nearly identical no matter who calculates it) to remain orthogonal to the CompCor regressors. Better statisticians than I (*cough* @jmumford) could probably tell you if there's anything to it or if I'm engaging in cargo cult stats.

**Comment by effigies** [comment]
Awesome. Sounds like you've got a good direction to go in, so I'm going to close this for now. If it turns out this is necessary for valid analysis, then we can revisit it.
