### ISSUE TITLE
boldref intensity 

### ISSUE THREAD

**Issue by michaelf500** [nipreps/fmriprep#3055]
### What happened?

The intensity on the output functional sub-XX_ses-0X_task-XX_boldref.nii looks weird. Many values are negative, and there are some very bright areas. As though an unsigned integer image has been misinterpreted as a signed one.

All other files (images displayed in the output sub-XXX.html file, the functional images normalised to MNI space, the fmap images) look fine.
Original images are INT16 (and look fine. converted from dicom with dcm2niix v1.0.20220720 )

![Capture](https://github.com/nipreps/fmriprep/assets/23660426/b3038de1-c683-46e0-b01f-9863d9e64714)

### What command did you use?

```shell
fmriprep-docker /home/michael/S/Data/MRI/bids/ /home/michael/freesurfer/creed/ participant --participant-label CREEDPD18 --fs-license-file /home/michael/freesurfer/license.txt --ignore slicetiming --longitudinal -u 1009:1009
RUNNING: docker run --rm -e DOCKER_VERSION_8395080871=20.10.21 -it -u 1009:1009 -v /home/michael/freesurfer/license.txt:/opt/freesurfer/license.txt:ro -v /home/michael/S/Data/MRI/bids:/data:ro -v /home/michael/freesurfer/creed:/out nipreps/fmriprep:23.0.0 /data /out participant --participant-label CREEDPD18 --ignore slicetiming --longitudinal
```

### What version of fMRIPrep are you running?

23.0.0

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment]
This is pretty surprising. Would you be able to share a minimal dataset that reproduces this?

**Comment by michaelf500** [comment]
Interestingly, if I run the same command but first divide the functional scan by 100, all looks fine. 
Happy to share a dataset - I've included two runs, the first is the original functional scan (which displays the problem) and the second run is the same thing divided by 100 (and which doesn't). Some more details in the README 
[intensity_check.tar.gz](https://github.com/nipreps/fmriprep/files/12014230/intensity_check.tar.gz)

**Comment by effigies** [comment]
Interesting. My first guess would be that this is an issue with saving out the boldref doing some unsafe casting, since it doesn't seem to have affected processing.

I will have a look at this as I can, but it's hard to commit to anything before August at this point. Please bug me if I don't get back to you by early August.

**Comment by michaelf500** [comment]
Hi

Just wondering if you had a chance to look at this?

Thanks
Michael

**Comment by effigies** [comment]
I have reproduced it. Looking through the working directory the reference generation is fine. The problem seems to be related to trying to save the data file back out as the input types, but we end up casting rather than letting nibabel do scaling. In nipreps/niworkflows#821 I 'm just going to switch it to float32, because it really doesn't matter enough to be worth the headache of fixing the int logic for scaled data.
