### ISSUE TITLE
Large Number of Masked Out Voxels in ME Data

### ISSUE THREAD

**Issue by rylandm** [nipreps/fmriprep#3057]
### What happened?

I'm using fmriprep to preprocess ME data, using the `--me-output-echos` option. The "desc-preproc_bold.nii.gz" files have a number of voxels masked out that are included in the "desc-brain_mask.nii.gz". Both the "boldref.nii.gz" image and the "echo-#_desc-preproc_bold.nii.gz" images do not have this issue. For some runs there are only a few voxels masked out, but for others a significant part of the brain is missing (screenshot below from a particularly bad session). My understanding is that to create the OC image, fmriprep uses the tedana_workflow, which will automatically generate a mask if one is not provided. Since the OC images don't match the fmriprep generated brain mask, I think that it must be using a Tedana generated mask. I mentioned this to @oesteban and he said if this is the case, then it is probably a bug. If it is the intended behavior, it would be great to have an option to use the fmriprep brain mask instead. We've found the Tedana automatic masks to be unsatisfactory in too many cases. Thanks! 

### What command did you use?

```shell
singularity run --cleanenv \
    -B ${bids_data}:/input \
    -B ${bids_derivatives}:/output \
    -B ${work_dir}:/work \
    -B ${freesurfer_license}:/license.txt \
    -B ${fmriprep_filter}:/fmriprep_filter.json \
    fmriprep-23.0.2.simg \
    /input /output \
    participant \
    --fs-license-file /license.txt \
    --skip_bids_validation \
    --participant-label $subject \
    --task-id rest \
    --bids-filter-file /fmriprep_filter.json \
    --work-dir /work \
    --fs-subjects-dir /output/sourcedata/freesurfer \
    --output-spaces fsaverage MNI152NLin6Asym fsLR func T1w fsnative \
    --nprocs 16 \
    --omp-nthreads 16 \
    --cifti-output 91k \
    --me-output-echos \
    --force-bbr \
    --ignore slicetiming \
    --dummy-scans 10 \
    --return-all-components \
    --fd-spike-threshold 0.2
```

### What version of fMRIPrep are you running?

23.0.2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

FreeSurfer

### Additional information / screenshots

This is an overlay of sub-007_ses-08_task-rest_run-01_desc-brain_mask.nii.gz on top of sub-007_ses-08_task-rest_run-01_desc-preproc_bold.nii.gz:
![sub-007_ses-08_task-rest_run-01_desc-brain_mask_on_desc-preproc_bold](https://github.com/nipreps/fmriprep/assets/17263743/cd9485f1-d19d-47d3-846b-c20046ddb35a)

**Comment by effigies** [comment]
The optimal combination is only defined where the T2star map can be calculated. We can't really pick and choose masks here.

**Comment by oesteban** [comment]
Thanks @rylandm for posting this. @effigies, we had a zoom call and asked him to report the problem.

In that call, something became apparent to me, which is, why are we calculating the optimal combination at all?

The problem is that it looks like the optimal combination is very sensitive to the processed echoes, so it might not make a lot of sense to provide it as an output of fMRIPrep.

However, we would need to rethink some parts of the reports. One idea we got is that we could generate the carpet plot on the optimal combination (as I believe we do currently), but also provide carpetplots for each echo. The individual-echo carpets would be folded by default, so that the report doesn't become an eternal scrolling timesink.

WDYT?

**Comment by oesteban** [comment]
(this idea came around by the fact that the optimal combination's carpet already shows those voids where the combination didn't work)

**Comment by effigies** [comment]
> why are we calculating the optimal combination at all?

I will defer to @tsalo and @emdupre on whether it's ever reasonable to use the optimal combination without taking the individual echos to tedana for denoising. Maybe it was better than nothing when it was first implemented and is now just a holdover that might as well be removed, maybe there's still a use case there.



> One idea we got is that we could generate the carpet plot on the optimal combination (as I believe we do currently), but also provide carpetplots for each echo. The individual-echo carpets would be folded by default, so that the report doesn't become an eternal scrolling timesink.

If I had to guess, I'd say the middle echo would probably be reasonably representative and save the trouble of multiple carpetplots, but sure we could also generate multiple and collapse them.

This reminds me: What is a good way of generating carpetplots if we want to do a minimal workflow (and do not want to resample the whole time series)? There's decimation of the final time series that could possibly be done before resampling to save time and space, but I don't know if any tool would do it for us, or if we would need to implement it ourselves with nitransforms.

**Comment by emdupre** [comment]
> I will defer to @tsalo and @emdupre on whether it's ever reasonable to use the optimal combination without taking the individual echos to tedana for denoising. 

I know of several groups that just want the optimal combination (_not_ the TE-informed, ICA-denoised timeseries), in which case it's not something that can easily be calculated after fMRIPrep, because it's broadly recommended to be done only after HMC and STC. Maybe @tsalo has updated recommendations on where this can be calculated, though.

> (this idea came around by the fact that the optimal combination's carpet already shows those voids where the combination didn't work)

This isn't a problem with the combination not working, but with the adaptive masking procedure which is [a known issue with some datasets.](https://github.com/ME-ICA/tedana/issues/898#issue-1453460191) The most recently recommended procedure (that I've seen) is to provide an existing mask directly to tedana. In that case, the provided brain mask is used to calculate good signal rather than using `compute_epi_mask` from Nilearn on the first echo, which can fail as shown in the included plot.

To avoid data loss the T2* map can be calculated where only one echo has good signal, and that's already implemented (as described in the Note [here](https://tedana.readthedocs.io/en/stable/approach.html#monoexponential-decay-model-fit)). So, I imagine this is really about the signal quality in the first echo that's used to calculate the mask.

If you try explicitly providing a brainmask to the combination (maybe re-running just the tedana t2s workflow using the fMRIPrep working directory outputs), do you still see this issue ?

**Comment by CesarCaballeroGaudes** [comment]
Regarding the utility of the optimal combination (OC), my opinion is that this dataset is the most recommendable to perform subsequent conventional analyses (for example, GLM or FC analyses) with ME-fMRI data. Therefore, I would recommend keeping it as the default option for ME-fMRI. Furthermore, both PCA and ICA decompositions in TEDANA are performed on the OC dataset. 

As @emdupre indicates, the main issue is with the adaptive masking that is computed by TEDANA if no mask is given as input. This mask is computed on the basis that there is "good" signal in a sufficient number of echoes.  But, the threshold for "goodness" might be too strict in certain cases as we are experiencing. In fact, we always input our own masks when calling TEDANA in our scripts. Since the mask generated by fMRIprep is appropriate in most cases, the simplest solution would be that the tedana workflow in fMRIprep allows using this brain mask instead. 

> If you try explicitly providing a brainmask to the combination (maybe re-running just the tedana t2s workflow using the fMRIPrep working directory outputs), do you still see this issue ?

@emdupre How can we do that with fMRIprep? In other words, how can we run subparts of the fMRIprep pipeline? or are you suggesting to directly run TEDANA on the fMRIprep directory outputs?

> let me know what you think on the four items (whether optimal combination should be calculated by fMRIPrep, whether the carpet would be better on the middle echo, and notes 1 and 2).

I would keep the carpet plot of the optimally combined signal. As noted before, this is the most widely-used dataset when one collects ME-fMRI data.

Having the carpetplots of the different echoes can provide useful information about signal fluctuations. For example, fluctuations related to changes in net magnetization will be more apparent in the shortest echoes, whereas CSF fluctuations might be more apparent in the longest echoes since T2* values in CSF are much longer than in GM and WM. As suggested, these carpetplots could be added in tabs or folded so that they don't take a lot of space. 
For the same reasons

**Comment by oesteban** [comment]
Thanks! It seems pretty clear, the first thing on the TODO list is now
making sure we pass the mask into the OC  calculation node.

**Comment by CesarCaballeroGaudes** [comment]
I agree, but I would add it as an optional argument so that the user can choose which mask they want to use

**Comment by effigies** [comment]
We do pass the fMRIPrep-calculated BOLD mask into T2SMap, which gets translated to the `--mask` flag in `t2smap`. In 23.1, we began dilating the mask by a couple voxels, because ours could sometimes be overly conservative.

We are pinned to tedana 0.0.13, in case that makes a difference. I haven't looked into what the shift to calver means for us.

**Comment by rylandm** [comment]
Thank you for all the responses everyone. The issue with `compute_epi_mask` that @emdupre brought up is what I'm worried is happening, sorry if that wasn't clear. As suggested, I manually ran Tedana's `t2smap` passing it the fmriprep brain mask and the echoes generated by the `--me-output-echos` option from fmriprep. The issue appears to go away (see screenshot below). @effigies Is there any chance that the fmriprep mask should be getting passed to `t2smap`, but isn't and it's using adaptive mask instead?
![fmriprep_brain_mask_on_manually_computed_oc_image](https://github.com/nipreps/fmriprep/assets/17263743/7ee15eb3-d919-42db-b58a-04053ee6d565)

**Comment by rylandm** [comment]
Unfortunately, I've been deleting the work directory after I run fmriprep because of space concerns. I'm rerunning the session now, I'll take a look when it finishes.

**Comment by rylandm** [comment]
Sorry for the delay, the `t2smap` command is below. As you said, it is providing a mask to t2smap, but I opened it up and it's not the `sub-007_ses-08_task-rest_run-01_desc-brain_mask.nii.gz`. I've attached an image below of the mask overlaid on the first echo image being passed to t2smap. I'm going to update to 23.1 and see if that improves the mask, I think some of the runs will be improved by a couple voxel dilation, but this run seems like it might be a different issue. I'm able to get a reasonable result by running `t2smap` manually, if updating to 23.1 doesn't solve the issue, is there a way I can run fmriprep and give it the OC image I want it to use rather than have it compute one?
```
t2smap \
    -d /work/fmriprep_23_0_wf/single_subject_007_wf/func_preproc_ses_08_task_rest_run_01_echo_1_wf/bold_bold_trans_wf/_echoidx_0/merge/vol0000_xform-00000_clipped_merged.nii.gz \
       /work/fmriprep_23_0_wf/single_subject_007_wf/func_preproc_ses_08_task_rest_run_01_echo_1_wf/bold_bold_trans_wf/_echoidx_1/merge/vol0000_xform-00000_clipped_merged.nii.gz \
       /work/fmriprep_23_0_wf/single_subject_007_wf/func_preproc_ses_08_task_rest_run_01_echo_1_wf/bold_bold_trans_wf/_echoidx_2/merge/vol0000_xform-00000_clipped_merged.nii.gz \
       /work/fmriprep_23_0_wf/single_subject_007_wf/func_preproc_ses_08_task_rest_run_01_echo_1_wf/bold_bold_trans_wf/_echoidx_3/merge/vol0000_xform-00000_clipped_merged.nii.gz \
       /work/fmriprep_23_0_wf/single_subject_007_wf/func_preproc_ses_08_task_rest_run_01_echo_1_wf/bold_bold_trans_wf/_echoidx_4/merge/vol0000_xform-00000_clipped_merged.nii.gz \
    -e 10.6 28.69 46.78 64.86999999999999 82.96000000000001 \
    --mask /work/fmriprep_23_0_wf/single_subject_007_wf/func_preproc_ses_08_task_rest_run_01_echo_1_wf/initial_boldref_wf/enhance_and_skullstrip_bold_wf/combine_masks/sub-007_ses-08_task-rest_run-01_echo-1_bold_valid_average_corrected_brain_mask_maths.nii.gz \
    --fittype curvefit
```
![sub-007_ses-08_task-rest_run-01_echo-1_bold_valid_average_corrected_brain_mask_maths_on_vol0000_xform-0000_clipped_merged](https://github.com/nipreps/fmriprep/assets/17263743/03afabc6-9e60-4b1a-90e3-44a3f7f6224e)

**Comment by rylandm** [comment]
Apparently the change in 23.1 is enough. I updated to 23.1.3 and ran that run and the mask is good. I'll run the rest of the dataset with 23.1 to make sure, but it seems like updating solves it. Thanks for your help!

**Comment by effigies** [comment]
I don't see much to do here at this point, but if this crops up again, please reopen.
